[source.crates-io]
replace-with = "tuna"

# 清华大学
[source.tuna]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"
# home = "https://mirrors.tuna.tsinghua.edu.cn/help/crates.io-index/"

# 中国科技大学
[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"
# home = "https://mirrors.ustc.edu.cn/crates.io-index/"

# 上海交通大学
[source.sjtu]
registry = "sparse+https://mirrors.sjtug.sjtu.edu.cn/crates.io-index/"
# home = "https://mirrors.sjtug.sjtu.edu.cn/docs/crates.io"

# rust 中文社区
[source.rustcc]
registry = "git://crates.rustcc.cn/crates.io-index"
# home = "https://rustcc.cn/"

# 字节跳动
[source.rsproxy]
registry = "sparse+https://rsproxy.cn/index/"
# home = "https://rsproxy.cn/"